# Generated by Django 2.2.4 on 2020-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='content_test',
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
